### ISSUE TITLE
THCudaCheck FAIL THCTensorMath.cu error=8 : invalid device function on Titan X

### ISSUE THREAD

**Issue by MandarGogate** [facebookresearch/SparseConvNet#3]
I get following error when I run hello-world.py

```
THCudaCheck FAIL file=/py/conda-bld/pytorch_1493676237139/work/torch/lib/THC/generic/THCTensorMath.cu line=35 error=8 : invalid device function
Traceback (most recent call last):
  File "hello-world.py", line 54, in <module>
    output = model.forward(input)
  File "/home/mgo/miniconda2/lib/python2.7/site-packages/torch/legacy/nn/Module.py", line 33, in forward
    return self.updateOutput(input)
  File "/home/mgo/miniconda2/lib/python2.7/site-packages/torch/legacy/nn/Sequential.py", line 36, in updateOutput
    currentOutput = module.updateOutput(currentOutput)
  File "/home/mgo/miniconda2/lib/python2.7/site-packages/torch/legacy/nn/Sequential.py", line 36, in updateOutput
    currentOutput = module.updateOutput(currentOutput)
  File "/home/mgo/Desktop/SparseConvNet/PyTorch/sparseconvnet/legacy/validConvolution.py", line 46, in updateOutput
    torch.cuda.IntTensor() if input.features.is_cuda else nullptr)
  File "/home/mgo/miniconda2/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 177, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: cuda runtime error (8) : invalid device function at /py/conda-bld/pytorch_1493676237139/work/torch/lib/THC/generic/THCTensorMath.cu:35
```

P.S. I don't get any errors when I run hello-world.lua or VGGplus.lua or any other PyTorch example

**Comment by btgraham** [comment]
Thanks for the bug report.
Can I just check that by 'or any other PyTorch example' you mean that VGGplus.py works in Assamese_handwriting/ ? 
Does your computer have only one GPU?
When you run luarocks make, the output will include a couple of line a bit like:
"""
-- Generating /home/ben/SparseConvNet/Torch/build/CMakeFiles/cusparseconvnet.dir/SCN/./cusparseconvnet_generated_init.cu.o
/usr/local/cuda/bin/nvcc /home/ben/SparseConvNet/Torch/SCN/init.cu -c
-o /home/ben/SparseConvNet/Torch/build/CMakeFiles/cusparseconvnet.dir/SCN/./cusparseconvnet_generated_init.cu.o -ccbin /usr/bin/cc -m64
--std c++11 -Dcusparseconvnet_EXPORTS -Xcompiler ,\"-fopenmp\",\"-fPIC\",\"-O3\",\"-DNDEBUG\"
-gencode arch=compute_52,code=sm_52 -gencode arch=compute_20,code=sm_21 -DNVCC -I/usr/local/cuda/include
-I/home/ben/torch/install/include -I/home/ben/torch/install/include/TH -I/home/ben/SparseConvNet/Torch
-I/home/ben/SparseConvNet/Torch/../PyTorch/sparseconvnet/SCN -I/home/ben/torch/install/include/THC -I/usr/local/cuda/include
"""
Can you please paste what you get on your machine for that?

**Comment by MandarGogate** [comment]
@btgraham Thank you for the prompt response.

> Can I just check that by 'or any other PyTorch example' you mean that VGGplus.py works in Assamese_handwriting/ ?

Any other PyTorch means any example which does not include SparseConvNet library.
None of the python examples in the example directory works (including VGGplus.py in Assamese_handwriting).

> Does your computer have only one GPU?

Yes

> When you run luarocks make, the output will include a couple of line a bit like:

-- Generating /home/mgo/Downloads/SparseConvNet/Torch/build/CMakeFiles/cusparseconvnet.dir/SCN/./cusparseconvnet_generated_init.cu.o
/usr/local/cuda-8.0/bin/nvcc /home/mgo/Downloads/SparseConvNet/Torch/SCN/init.cu -c -o /home/mgo/Downloads/SparseConvNet/Torch/build/CMakeFiles/cusparseconvnet.dir/SCN/./cusparseconvnet_generated_init.cu.o -ccbin /home/mgo/miniconda3/bin/cc -m64 --std c++11 -Dcusparseconvnet_EXPORTS -Xcompiler ,\"-fopenmp\",\"-fPIC\",\"-O3\",\"-DNDEBUG\" -gencode arch=compute_61,code=sm_61 -DNVCC -I/usr/local/cuda-8.0/include -I/home/mgo/torch/install/include -I/home/mgo/torch/install/include/TH -I/home/mgo/Downloads/SparseConvNet/Torch -I/home/mgo/Downloads/SparseConvNet/Torch/../PyTorch/sparseconvnet/SCN -I/home/mgo/torch/install/include/THC -I/usr/local/cuda-8.0/include

**I solved the issue by changing** `-gencode arch=compute_52,code=sm_52 -gencode arch=compute_30,code=sm_30` **in the setup.py file with** `-gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=sm_61 -gencode=arch=compute_62,code=sm_62`.

For CUDA 8 maximum compatibility the arguments would be:
```
-arch=sm_30 \
 -gencode=arch=compute_20,code=sm_20 \
 -gencode=arch=compute_30,code=sm_30 \
 -gencode=arch=compute_50,code=sm_50 \
 -gencode=arch=compute_52,code=sm_52 \
 -gencode=arch=compute_52,code=compute_52 \
 -gencode=arch=compute_60,code=sm_60 \
 -gencode=arch=compute_61,code=sm_61 \
 -gencode=arch=compute_62,code=sm_62 \
```

Please correct me if I am wrong.

**Comment by btgraham** [comment]
setup.py updated, thanks

**Comment by Saleh-Gholam-Zadeh** [comment]
Hi Guys
I have exactly same problem 
but when type   luarocks make   in the terminal  I face  this error 
"Error: Argument missing: please specify a rockspec to use on current directory."
in which directory I shoud type "luarocks make"

This is the command and the error that I get

$ CUDA_VISIBLE_DEVICES=0 python2 ./example/main.py --dataset mpii --a
rch hg --stack 8 --block 1 --features 256 --checkpoint ./checkpoint/mpii/hg-s8-b1 --anno-path "/home/saleh/Documents/terme4_master/semester_proj/pytorch_pose/pytorch-pose/data/mpii/mpii_selected_annotations_debug.json" --image-path /home/saleh/Documents/terme4_master/semester_proj/pytorch_pose/pytorch-pose/short_list --epochs 5 -d
/home/saleh/anaconda3/envs/py27/lib/python2.7/site-packages/torch/cuda/__init__.py:117: UserWarning: 
    Found GPU0 GeForce GT 710M which is of cuda capability 2.1.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
GeForce GT 710M
==> creating model 'hg', stacks=8, blocks=1
    Total params: 25.59M
    Mean: 0.4404, 0.4440, 0.4327
    Std:  0.2458, 0.2410, 0.2468

Epoch: 1 | LR: 0.00025000
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1549614443593/work/aten/src/THC/generic/THCTensorMath.cu line=14 error=8 : invalid device function
Traceback (most recent call last):
  File "./example/main.py", line 434, in <module>
    main(parser.parse_args())
  File "./example/main.py", line 154, in main
    args.debug, args.flip)
  File "./example/main.py", line 200, in train
    output = model(input)
  File "/home/saleh/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/saleh/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/saleh/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/saleh/Documents/terme4_master/semester_proj/pytorch_pose/pytorch-pose/example/../pose/models/hourglass.py", line 158, in forward
    x = self.conv1(x)
  File "/home/saleh/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/saleh/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (8) : invalid device function at /opt/conda/conda-bld/pytorch_1549614443593/work/aten/src/THC/generic/THCTensorMath.cu:14

**Comment by btgraham** [comment]
Lua Torch is no longer supported, so please install using python 3/conda.
